# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daffany Clark
email: daffany@daffanyclark.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social media
social:
- url: http://resumes.actorsaccess.com/daffanyclark
  icon: actors-access
  name: actors access

- url: http://www.imdb.com/name/nm3554141/
  icon: imdb
  name: IMDb

- url: https://www.facebook.com/daffanymclark
  icon: facebook
  name: Facebook

- url: https://twitter.com/daffanymclark
  icon: twitter
  name: Twitter

- url: https://instagram.com/daffmc29/
  icon: instagram
  name: Instagram

- url: http://www.whosay.com/daffanyclark
  icon: whosay
  name: WhoSay


# Build settings
markdown: kramdown

collections:
  - collection-filmography
  - collection-giving
